namespace: ${namespace}
cfngin_bucket: ${cfngin_bucket}

common_tags: &common_tags
  namespace: ${namespace}
  provisioner: 'cloudformation'


stacks:
  stno-hub:
    template_path: templates/aws-transit-network-orchestrator-hub.yaml
    enabled: ${enable_stack_changes}
    termination_protection: ${enable_stack_termination_protection}
    variables: 
      Principals: ${Principals} 
      PrincipalType: ${PrincipalType}
      ApprovalNotification: ${ApprovalNotification}
      ApprovalNotificationEmail: ${ApprovalNotificationEmail}
      UserPoolUsernameForAdminUser: ${UserPoolUsernameForAdminUser}
      UserPoolUsernameForReadOnlyUser: ${UserPoolUsernameForReadOnlyUser}
      ConsoleLoginInformationEmail: ${ConsoleLoginInformationEmail}
      AttachmentTag: ${AttachmentTag}
      AssociationTag: ${AssociationTag}
      PropagationTag: ${PropagationTag}
      TgwPeeringTag: ${TgwPeeringTag}
      DefaultRoute: ${DefaultRoute}
      ListOfCustomCidrBlocks: ${ListOfCustomCidrBlocks}
      CustomerManagedPrefixListIds: ${CustomerManagedPrefixListIds}
      ExistingTransitGatewayId: ${ExistingTransitGatewayId}
      ExistingGlobalNetworkId: ${ExistingGlobalNetworkId}
      ListOfVpcTagsForAttachment: ${ListOfVpcTagsForAttachment}
      OrganizationManagementAccountRoleArn: ${OrganizationManagementAccountRoleArn}
      CognitoDomainPrefixParameter: ${CognitoDomainPrefixParameter}
      CognitoSAMLProviderNameParameter: ${CognitoSAMLProviderNameParameter}
      CognitoSAMLProviderMetadataUrlParameter: ${CognitoSAMLProviderMetadataUrlParameter}
      AllowListedRanges: ${AllowListedRanges}
    tags:
      <<: *common_tags