---
service: ${env:stack} 
#variablesResolutionMode: 20210326
#unresolvedVariablesNotificationMode: error

plugins:
  - serverless-plugin-resource-tagging


provider:
  name: aws
  region: ${opt:region}
  stage: ${opt:stage}
  deploymentBucket:
    name: ${env:deployment_bucket}
    serverSideEncryption: AES256
  logRetentionInDays: 30
  iam: ${file(${self:provider.environment.sls_stack_path}/stack-config.yaml):permissions}
  environment:
    sls_stack_path: src/stacks/${env:stack, 'dummy'}
  stackTags:
    Namespace: ${env:namespace} 
    Environment: ${opt:stage}
    Region: ${opt:region}
    Provisioner: 'serverless'


custom: ${file(${self:provider.environment.sls_stack_path}/stack-config.yaml):custom}

functions: ${file(${self:provider.environment.sls_stack_path}/stack-config.yaml):functions}

resources: ${file(${self:provider.environment.sls_stack_path}/stack-config.yaml):resources}