---

commons:
  timeout: 10
  memorySize: 128

  DUMMY_MSG: "Hello World: Commons"

sandbox:
  timeout: 10
  memorySize: 128

  DUMMY_MSG: "Hello World: Sandbox"

develop:
  timeout: 10
  memorySize: 128

  DUMMY_MSG: "Hello World: Develop"

staging:
  timeout: 10
  memorySize: 128

  DUMMY_MSG: "Hello World: Staging"

product:
  timeout: 10
  memorySize: 128

  DUMMY_MSG: "Hello World: Product"
