namespace: ${namespace}
cfngin_bucket: ${cfngin_bucket}

common_tags: &common_tags
  namespace: ${namespace}
  provisioner: 'cloudformation'


stacks:
  stno-organization-role:
    template_path: templates/aws-transit-network-orchestrator-organization-role.yaml
    enabled: ${enable_stack_changes}
    termination_protection: ${enable_stack_termination_protection}
    variables:
      HubAccount: ${HubAccount}
      RoleName: ${RoleName}
    tags:
      <<: *common_tags