namespace: ${namespace}
cfngin_bucket: ${cfngin_bucket}

common_tags: &common_tags
  namespace: ${namespace}
  provisioner: 'cloudformation'


stacks:
  terraform-state:
    template_path: templates/backend.yaml
    termination_protection: true
    variables:
      pTerraformStateBucketPrefix: ${namespace}-terraform-state
      pTerraformStateLockTableName: ${namespace}-terraform-state-lock
    tags:
      <<: *common_tags