namespace: ${namespace}
cfngin_bucket: ${cfngin_bucket}

common_tags: &common_tags
  namespace: ${namespace}
  provisioner: 'cloudformation'


stacks:
  stno-spoke:
    template_path: templates/aws-transit-network-orchestrator-spoke.yaml
    termination_protection: true
    variables:
      HubAccount: ${HubAccount}
      CreateServiceRoleForVPCTransitGateway: ${CreateServiceRoleForVPCTransitGateway}
    tags:
      <<: *common_tags