namespace: ${namespace}
cfngin_bucket: ${cfngin_bucket}

common_tags: &common_tags
  namespace: ${namespace}
  provisioner: 'cloudformation'


stacks:
  serverless-state:
    template_path: templates/backend.yaml
    enabled: ${enable_stack_changes}
    termination_protection: ${enable_stack_termination_protection}
    variables:
      pStateBucketPrefix: ${namespace}-serverless-state
    tags:
      <<: *common_tags